-- Mock Danışman Oluştur
insert into agents (name, email, password_hash, phone, photo, title, role, is_active)
values (
  'Ahmet Yılmaz',
  'ahmet@alfaemlak.com',
  encode(digest('ahmet123' || 'alfa_salt_2024', 'sha256'), 'hex'),
  '+90 533 123 4567',
  '',
  'Kıdemli Emlak Danışmanı',
  'AGENT',
  true
)
on conflict (email) do nothing;

-- Mock İlan Oluştur (önce agents id'sini al)
insert into listings (
  listing_id,
  title,
  kind,
  property_type,
  city,
  region,
  neighborhood,
  full_address,
  price,
  currency,
  description_tr,
  description_en,
  cover_image,
  bedrooms,
  bathrooms,
  area_m2,
  plot_area_m2,
  floor,
  building_age,
  living_rooms,
  has_pool,
  has_garden,
  has_fireplace,
  has_parking,
  furnished,
  sea_view,
  features,
  badges,
  virtual_tour_url,
  video_url,
  latitude,
  longitude,
  map_enabled,
  nearby_places,
  nearby_enabled,
  publish_status,
  views,
  favorites_count,
  rating,
  consultant_name,
  consultant_phone,
  consultant_email,
  consultant_office,
  consultant_photo,
  consultant_whatsapp,
  stats_show_views,
  stats_show_favs,
  stats_show_rating,
  translations
)
select
  'AE-2026-99999',
  'Girne Deniz Manzaralı Lüks Villa',
  'SATILIK',
  'Villa',
  'Girne',
  'Esentepe',
  'Koru',
  'Koru Mevkii, Deniz Caddesi No:42, Esentepe, Girne',
  285000,
  'EUR',
  'Deniz manzaralı, özel havuzlu lüks villa. 4 yatak odası, geniş salon, modern mutfak. Site içinde 7/24 güvenlik.',
  'Luxury villa with sea view, private pool. 4 bedrooms, spacious living room, modern kitchen. 24/7 security.',
  '',
  4,
  3,
  220,
  500,
  '2',
  2,
  1,
  true,
  true,
  true,
  true,
  false,
  true,
  '["Özel Havuz", "Deniz Manzarası", "Akıllı Ev Sistemi", "Merkezi Klima", "Güvenlik Kameraları", "Jeneratör", "Otopark"]'::jsonb,
  '{"featured": true, "exclusive": true, "virtualTour": false, "video": false, "new": true, "priceDrop": false}'::jsonb,
  null,
  null,
  35.3364,
  33.2547,
  true,
  '[]'::jsonb,
  true,
  'PUBLISHED',
  142,
  23,
  4.8,
  'Ahmet Yılmaz',
  '+90 533 123 4567',
  'ahmet@alfaemlak.com',
  'Alfa Emlak Girne Ofisi',
  '',
  '+90 533 123 4567',
  true,
  true,
  false,
  '{"en": {"title": "Luxury Sea View Villa in Kyrenia", "shortDescription": "Deniz manzaralı özel havuzlu lüks villa", "longDescription": "Luxury villa with sea view, private pool. 4 bedrooms, spacious living room, modern kitchen."}, "ru": {"title": "Роскошная вилла с видом на море в Кирении", "shortDescription": "Роскошная вилла с видом на море и бассейном", "longDescription": "Роскошная вилла с видом на море, частным бассейном. 4 спальни."}}'::jsonb
on conflict (listing_id) do nothing;
