-- CreateTable
CREATE TABLE "Listing" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "listingId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "propertyType" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "region" TEXT NOT NULL,
    "neighborhood" TEXT,
    "fullAddress" TEXT,
    "price" REAL NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'EUR',
    "shortDescription" TEXT,
    "longDescription" TEXT,
    "coverImage" TEXT,
    "bedrooms" INTEGER,
    "bathrooms" INTEGER,
    "areaM2" REAL,
    "plotAreaM2" REAL,
    "floor" TEXT,
    "buildingAge" INTEGER,
    "livingRooms" INTEGER,
    "hasPool" BOOLEAN,
    "hasGarden" BOOLEAN,
    "hasFireplace" BOOLEAN,
    "hasParking" BOOLEAN,
    "furnished" BOOLEAN,
    "seaView" BOOLEAN,
    "detailFields" TEXT,
    "badgeFeatured" BOOLEAN NOT NULL DEFAULT false,
    "badgeExclusive" BOOLEAN NOT NULL DEFAULT false,
    "badgeVirtualTour" BOOLEAN NOT NULL DEFAULT false,
    "badgeVideo" BOOLEAN NOT NULL DEFAULT false,
    "badgeNew" BOOLEAN NOT NULL DEFAULT false,
    "badgePriceDrop" BOOLEAN NOT NULL DEFAULT false,
    "features" TEXT,
    "virtualTourUrl" TEXT,
    "virtualTourEnabled" BOOLEAN NOT NULL DEFAULT false,
    "videoUrl" TEXT,
    "videoEnabled" BOOLEAN NOT NULL DEFAULT false,
    "lat" REAL,
    "lng" REAL,
    "mapEnabled" BOOLEAN NOT NULL DEFAULT false,
    "nearbyPlaces" TEXT,
    "nearbyEnabled" BOOLEAN NOT NULL DEFAULT false,
    "consultantName" TEXT,
    "consultantPhoto" TEXT,
    "consultantWhatsapp" TEXT,
    "consultantPhone" TEXT,
    "consultantEmail" TEXT,
    "consultantOffice" TEXT,
    "consultantOfficeLogo" TEXT,
    "publishStatus" TEXT NOT NULL DEFAULT 'DRAFT',
    "views" INTEGER NOT NULL DEFAULT 0,
    "favoritesCount" INTEGER NOT NULL DEFAULT 0,
    "rating" REAL,
    "statsShowViews" BOOLEAN NOT NULL DEFAULT true,
    "statsShowFavs" BOOLEAN NOT NULL DEFAULT true,
    "statsShowRating" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "ListingImage" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "listingId" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "ListingImage_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "SiteSettings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "siteName" TEXT NOT NULL DEFAULT 'ALFA EMLAK',
    "logoUrl" TEXT,
    "phone" TEXT,
    "whatsapp" TEXT,
    "email" TEXT,
    "address" TEXT,
    "socialJson" TEXT,
    "footerAbout" TEXT,
    "seoTitle" TEXT,
    "seoDescription" TEXT,
    "heroTitle" TEXT,
    "heroSubtitle" TEXT,
    "defaultConsultantJson" TEXT,
    "menuJson" TEXT,
    "updatedAt" DATETIME NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Listing_listingId_key" ON "Listing"("listingId");
