export const kktcCityCoords: Record<string, { lat: number; lng: number; zoom: number }> = {
  lefkosa: { lat: 35.1856, lng: 33.3823, zoom: 13 },
  girne: { lat: 35.3365, lng: 33.3173, zoom: 13 },
  gazimagusa: { lat: 35.1250, lng: 33.9500, zoom: 13 },
  iskele: { lat: 35.2868, lng: 33.8821, zoom: 13 },
  lefke: { lat: 35.1118, lng: 32.8488, zoom: 13 },
  guzelyurt: { lat: 35.1997, lng: 32.9926, zoom: 13 },
};

export const kktcRegionCoords: Record<string, { lat: number; lng: number; zoom: number }> = {
  // İskele regions
  "long-beach": { lat: 35.2750, lng: 33.9000, zoom: 15 },
  "yeni-erenkoy": { lat: 35.5390, lng: 34.1950, zoom: 15 },
  "bogaz": { lat: 35.3130, lng: 33.9500, zoom: 15 },
  "bafra": { lat: 35.3610, lng: 34.0410, zoom: 15 },
  "dipkarpaz": { lat: 35.5980, lng: 34.3850, zoom: 14 },
  
  // Girne regions
  "alsancak": { lat: 35.3430, lng: 33.2080, zoom: 15 },
  "lapta": { lat: 35.3470, lng: 33.1550, zoom: 15 },
  "ozankoy": { lat: 35.3130, lng: 33.3510, zoom: 15 },
  "catalkoy": { lat: 35.3210, lng: 33.3930, zoom: 15 },
  "esentepe": { lat: 35.3480, lng: 33.5850, zoom: 15 },
  
  // Lefkoşa regions
  "gonyeli": { lat: 35.2160, lng: 33.3100, zoom: 15 },
  "taskinkoy": { lat: 35.2010, lng: 33.3420, zoom: 15 },
  "kucuk-kaymakli": { lat: 35.1950, lng: 33.3650, zoom: 15 },
  "dereboyu": { lat: 35.1940, lng: 33.3510, zoom: 16 },
  
  // Gazimağusa regions
  "maras": { lat: 35.1050, lng: 33.9420, zoom: 15 },
  "tuzla": { lat: 35.1700, lng: 33.9050, zoom: 15 },
  "yenibogazici": { lat: 35.2010, lng: 33.9010, zoom: 15 },
};

export const kktcCities = [
  { v: "", l: "Şehir seçin..." },
  { v: "lefkosa", l: "Lefkoşa" },
  { v: "girne", l: "Girne" },
  { v: "gazimagusa", l: "Gazimağusa" },
  { v: "iskele", l: "İskele" },
  { v: "lefke", l: "Lefke" },
  { v: "guzelyurt", l: "Güzelyurt" },
];

export const kktcRegions: Record<string, { v: string; l: string }[]> = {
  lefkosa: [
    { v: "alaykoy", l: "Alayköy" },
    { v: "balikesir", l: "Balıkesir" },
    { v: "demirhan", l: "Demirhan" },
    { v: "dereboyu", l: "Dereboyu" },
    { v: "dumlupinar", l: "Dumlupınar" },
    { v: "gonyeli", l: "Gönyeli" },
    { v: "hamitkoy", l: "Hamitköy" },
    { v: "haspolat", l: "Haspolat" },
    { v: "kizilbas", l: "Kızılbaş" },
    { v: "kumsal", l: "Kumsal" },
    { v: "kucuk-kaymakli", l: "Küçük Kaymaklı" },
    { v: "marmara", l: "Marmara" },
    { v: "minarelikoy", l: "Minareliköy" },
    { v: "ortakoy", l: "Ortaköy" },
    { v: "surlarici", l: "Surlariçi" },
    { v: "taskinkoy", l: "Taşkınköy" },
    { v: "yenisehir", l: "Yenişehir" },
    { v: "yenikent", l: "Yenikent" },
  ],
  girne: [
    { v: "agirdag", l: "Ağırdağ" },
    { v: "akcicek", l: "Akçiçek" },
    { v: "akdeniz", l: "Akdeniz" },
    { v: "alagadi", l: "Alagadi" },
    { v: "alemdag", l: "Alemdağ" },
    { v: "alsancak", l: "Alsancak" },
    { v: "arapkoy", l: "Arapköy" },
    { v: "asagi-girne", l: "Aşağı Girne" },
    { v: "bahceli", l: "Bahçeli" },
    { v: "bellapais", l: "Bellapais" },
    { v: "besparmak", l: "Beşparmak" },
    { v: "bogaz", l: "Boğaz" },
    { v: "camlibel", l: "Çamlıbel" },
    { v: "catalkoy", l: "Çatalköy" },
    { v: "dagyolu", l: "Dağyolu" },
    { v: "dikmen", l: "Dikmen" },
    { v: "dogankoy", l: "Doğanköy" },
    { v: "edremit", l: "Edremit" },
    { v: "efenditepe", l: "Efenditepe" },
    { v: "gecitkoy", l: "Geçitköy" },
    { v: "goceri", l: "Göçeri" },
    { v: "hisarkoy", l: "Hisarköy" },
    { v: "ilgaz", l: "Ilgaz" },
    { v: "incesu", l: "İncesu" },
    { v: "karaagac", l: "Karaağaç" },
    { v: "karakum", l: "Karakum" },
    { v: "karaolanoglu", l: "Karaoğlanoğlu" },
    { v: "karmi", l: "Karmi" },
    { v: "karsiyaka", l: "Karşıyaka" },
    { v: "kayalar", l: "Kayalar" },
    { v: "kilicaslan", l: "Kılıçaslan" },
    { v: "komurcu", l: "Kömürcü" },
    { v: "korucam", l: "Koruçam" },
    { v: "kozan", l: "Kozan" },
    { v: "lapta", l: "Lapta" },
    { v: "malatya", l: "Malatya" },
    { v: "girne-merkez", l: "Girne Merkez" },
    { v: "ozankoy", l: "Ozanköy" },
    { v: "pinarbasi", l: "Pınarbaşı" },
    { v: "sadrazamkoy", l: "Sadrazamköy" },
    { v: "sirinevler", l: "Şirinevler" },
    { v: "taskent", l: "Taşkent" },
    { v: "gungor", l: "Güngör" },
    { v: "tepebasi", l: "Tepebaşı" },
    { v: "turk-mahallesi", l: "Türk Mahallesi" },
    { v: "yesiltepe", l: "Yeşiltepe" },
    { v: "yukari-girne", l: "Yukarı Girne" },
    { v: "zeytinlik", l: "Zeytinlik" },
  ],
  gazimagusa: [
    { v: "gazimagusa-merkez", l: "Gazimağusa Merkez" },
    { v: "maras", l: "Maraş" },
    { v: "sakarya", l: "Sakarya" },
    { v: "karakol", l: "Karakol" },
    { v: "baykal", l: "Baykal" },
    { v: "dumlupinar", l: "Dumlupınar" },
    { v: "tuzla", l: "Tuzla" },
    { v: "mutluyaka", l: "Mutluyaka" },
    { v: "serdarli", l: "Serdarlı" },
    { v: "gecitkale", l: "Geçitkale" },
    { v: "yenibogazici", l: "Yeniboğaziçi" },
  ],
  iskele: [
    { v: "iskele-merkez", l: "İskele Merkez" },
    { v: "long-beach", l: "Long Beach" },
    { v: "bogaz", l: "Boğaz" },
    { v: "kalecik", l: "Kalecik" },
    { v: "bafra", l: "Bafra" },
    { v: "mehmetcik", l: "Mehmetçik" },
    { v: "dipkarpaz", l: "Dipkarpaz" },
    { v: "yeni-erenkoy", l: "Yeni Erenköy" },
    { v: "otuken", l: "Ötüken" },
    { v: "kuzucuk", l: "Kuzucuk" },
    { v: "turnalar", l: "Turnalar" },
    { v: "sinirustu", l: "Sınırüstü" },
  ],
  lefke: [
    { v: "lefke-merkez", l: "Lefke Merkez" },
    { v: "gemikonagi", l: "Gemikonağı" },
    { v: "yesilyurt", l: "Yeşilyurt" },
    { v: "doganci", l: "Doğancı" },
    { v: "akcay", l: "Akçay" },
    { v: "aydinkoy", l: "Aydınköy" },
    { v: "camlikoy", l: "Çamlıköy" },
    { v: "cengizkoy", l: "Cengizköy" },
    { v: "kozankoy", l: "Kozanköy" },
    { v: "taspinar", l: "Taşpınar" },
    { v: "baglikoy", l: "Bağlıköy" },
    { v: "yedidalga", l: "Yedidalga" },
  ],
  guzelyurt: [
    { v: "guzelyurt-merkez", l: "Güzelyurt Merkez" },
    { v: "gemikonagi", l: "Gemikonağı" },
    { v: "yesilyurt", l: "Yeşilyurt" },
    { v: "doganci", l: "Doğancı" },
    { v: "akcay", l: "Akçay" },
    { v: "aydinkoy", l: "Aydınköy" },
  ],
};
