export const kktcCityCoords: Record<string, { lat: number; lng: number; zoom: number }> = {
  lefkosa: { lat: 35.1856, lng: 33.3823, zoom: 13 },
  girne: { lat: 35.3365, lng: 33.3173, zoom: 13 },
  gazimagusa: { lat: 35.1250, lng: 33.9500, zoom: 13 },
  iskele: { lat: 35.2868, lng: 33.8821, zoom: 13 },
  lefke: { lat: 35.1118, lng: 32.8488, zoom: 13 },
  guzelyurt: { lat: 35.1997, lng: 32.9926, zoom: 13 },
};

export const kktcRegionCoords: Record<string, { lat: number; lng: number; zoom: number }> = {
  // İskele regions
  "long-beach": { lat: 35.2750, lng: 33.9000, zoom: 15 },
  "yeni-erenkoy": { lat: 35.5390, lng: 34.1950, zoom: 15 },
  "bogaz": { lat: 35.3130, lng: 33.9500, zoom: 15 },
  "bafra": { lat: 35.3610, lng: 34.0410, zoom: 15 },
  "dipkarpaz": { lat: 35.5980, lng: 34.3850, zoom: 14 },
  
  // Girne regions
  "alsancak": { lat: 35.3430, lng: 33.2080, zoom: 15 },
  "lapta": { lat: 35.3470, lng: 33.1550, zoom: 15 },
  "ozankoy": { lat: 35.3130, lng: 33.3510, zoom: 15 },
  "catalkoy": { lat: 35.3210, lng: 33.3930, zoom: 15 },
  "esentepe": { lat: 35.3480, lng: 33.5850, zoom: 15 },
  
  // Lefkoşa regions
  "gonyeli": { lat: 35.2160, lng: 33.3100, zoom: 15 },
  "taskinkoy": { lat: 35.2010, lng: 33.3420, zoom: 15 },
  "kucuk-kaymakli": { lat: 35.1950, lng: 33.3650, zoom: 15 },
  "dereboyu": { lat: 35.1940, lng: 33.3510, zoom: 16 },
  
  // Gazimağusa regions
  "maras": { lat: 35.1050, lng: 33.9420, zoom: 15 },
  "tuzla": { lat: 35.1700, lng: 33.9050, zoom: 15 },
  "yenibogazici": { lat: 35.2010, lng: 33.9010, zoom: 15 },
};

export const kktcCities = [
  { v: "", l: "Şehir seçin..." },
  { v: "lefkosa", l: "Lefkoşa" },
  { v: "girne", l: "Girne" },
  { v: "gazimagusa", l: "Gazimağusa" },
  { v: "iskele", l: "İskele" },
  { v: "guzelyurt", l: "Güzelyurt" },
  { v: "lefke", l: "Lefke" },
];

export const kktcRegions: Record<string, { v: string; l: string }[]> = {
  lefkosa: [
    { v: "akincilar", l: "Akıncılar" },
    { v: "alaykoy", l: "Alayköy" },
    { v: "balikesir", l: "Balıkesir" },
    { v: "batikent", l: "Batıkent" },
    { v: "beykoy", l: "Beyköy" },
    { v: "cihangir", l: "Cihangir" },
    { v: "caglayan", l: "Çağlayan" },
    { v: "cukurova", l: "Çukurova" },
    { v: "degirmenlik", l: "Değirmenlik" },
    { v: "demirhan", l: "Demirhan" },
    { v: "dilekkaya", l: "Dilekkaya" },
    { v: "dumlupinar", l: "Dumlupınar" },
    { v: "duzova", l: "Düzova" },
    { v: "erdemli", l: "Erdemli" },
    { v: "gazikoy", l: "Gaziköy" },
    { v: "gelibolu", l: "Gelibolu" },
    { v: "gocmenkoy", l: "Göçmenköy" },
    { v: "gokhan", l: "Gökhan" },
    { v: "gonyeli", l: "Gönyeli" },
    { v: "gurpinar", l: "Gürpınar" },
    { v: "hamitkoy", l: "Hamitköy" },
    { v: "haspolat", l: "Haspolat" },
    { v: "kalavac", l: "Kalavaç" },
    { v: "kanlikoy", l: "Kanlıköy" },
    { v: "kirklar", l: "Kırklar" },
    { v: "kizilbas", l: "Kızılbaş" },
    { v: "koskluciftlik", l: "Köşklüçiftlik" },
    { v: "kumsal", l: "Kumsal" },
    { v: "kucuk-kaymakli", l: "Küçük Kaymaklı" },
    { v: "lefkosa-surlarici", l: "Lefkoşa Surlariçi" },
    { v: "marmara", l: "Marmara" },
    { v: "meric", l: "Meriç" },
    { v: "metehan", l: "Metehan" },
    { v: "minarelikoy", l: "Minareliköy" },
    { v: "ortakoy", l: "Ortaköy" },
    { v: "sanayi-bolgesi", l: "Sanayi Bölgesi" },
    { v: "taskinkoy", l: "Taşkınköy" },
    { v: "turkeli", l: "Türkeli" },
    { v: "yenicekoy", l: "Yeniceköy" },
    { v: "yenikent", l: "Yenikent" },
    { v: "yenisehir", l: "Yenişehir" },
    { v: "yilmazkoy", l: "Yılmazköy" },
    { v: "yigitler", l: "Yiğitler" },
  ],
  girne: [
    { v: "agirdag", l: "Ağırdağ" },
    { v: "akcicek", l: "Akçiçek" },
    { v: "akdeniz", l: "Akdeniz" },
    { v: "alagadi", l: "Alagadi" },
    { v: "alemdag", l: "Alemdağ" },
    { v: "alsancak", l: "Alsancak" },
    { v: "arapkoy", l: "Arapköy" },
    { v: "asagi-girne", l: "Aşağı Girne" },
    { v: "bahceli", l: "Bahçeli" },
    { v: "bellapais", l: "Bellapais" },
    { v: "besparmak", l: "Beşparmak" },
    { v: "bogaz", l: "Boğaz" },
    { v: "camlibel", l: "Çamlıbel" },
    { v: "catalkoy", l: "Çatalköy" },
    { v: "dagyolu", l: "Dağyolu" },
    { v: "dikmen", l: "Dikmen" },
    { v: "dogankoy", l: "Doğanköy" },
    { v: "edremit", l: "Edremit" },
    { v: "esentepe", l: "Esentepe" },
    { v: "gecitkoy", l: "Geçitköy" },
    { v: "girne-merkez", l: "Girne Merkez" },
    { v: "goceri", l: "Göçeri" },
    { v: "hisarkoy", l: "Hisarköy" },
    { v: "ilgaz", l: "Ilgaz" },
    { v: "incesu", l: "İncesu" },
    { v: "karaagac", l: "Karaağaç" },
    { v: "karakum", l: "Karakum" },
    { v: "karaolanoglu", l: "Karaoğlanoğlu" },
    { v: "karmi", l: "Karmi" },
    { v: "karsiyaka", l: "Karşıyaka" },
    { v: "kayalar", l: "Kayalar" },
    { v: "kilicaslan", l: "Kılıçarslan" },
    { v: "korucam", l: "Koruçam" },
    { v: "kozan", l: "Kozan" },
    { v: "komurcu", l: "Kömürcü" },
    { v: "lapta", l: "Lapta" },
    { v: "malatya", l: "Malatya" },
    { v: "ozankoy", l: "Ozanköy" },
    { v: "pinarbasi", l: "Pınarbaşı" },
    { v: "sadrazamkoy", l: "Sadrazamköy" },
    { v: "sirinevler", l: "Şirinevler" },
    { v: "taskent", l: "Taşkent" },
    { v: "tepebasi", l: "Tepebaşı" },
    { v: "turk-mahallesi", l: "Türk Mahallesi" },
    { v: "yesiltepe", l: "Yeşiltepe" },
    { v: "yukari-girne", l: "Yukarı Girne" },
    { v: "zeytinlik", l: "Zeytinlik" },
  ],
  gazimagusa: [
    { v: "akdogan", l: "Akdoğan" },
    { v: "akova", l: "Akova" },
    { v: "alanici", l: "Alaniçi" },
    { v: "aridami", l: "Arıdamı" },
    { v: "aslankoy", l: "Aslanköy" },
    { v: "atlilar", l: "Atlılar" },
    { v: "baykal", l: "Baykal" },
    { v: "beyarmudu", l: "Beyarmudu" },
    { v: "canakkale", l: "Çanakkale" },
    { v: "cayonu", l: "Çayönü" },
    { v: "cinarli", l: "Çınarlı" },
    { v: "dortyol", l: "Dörtyol" },
    { v: "dumlupinar", l: "Dumlupınar" },
    { v: "gecitkale", l: "Geçitkale" },
    { v: "gonendere", l: "Gönendere" },
    { v: "gulseren", l: "Gülseren" },
    { v: "guvercinlik", l: "Güvercinlik" },
    { v: "inonu", l: "İnönü" },
    { v: "kaleici", l: "Kaleiçi" },
    { v: "karakol", l: "Karakol" },
    { v: "korkuteli", l: "Korkuteli" },
    { v: "koprulu", l: "Köprülü" },
    { v: "kurudere", l: "Kurudere" },
    { v: "kucuk-erenkoy", l: "Küçük Erenköy" },
    { v: "magusa-merkez", l: "Mağusa Merkez" },
    { v: "mallidag", l: "Mallıdağ" },
    { v: "maras", l: "Maraş" },
    { v: "mormenekse", l: "Mormenekşe" },
    { v: "murataga", l: "Muratağa" },
    { v: "mutluyaka", l: "Mutluyaka" },
    { v: "nergisli", l: "Nergisli" },
    { v: "pasakoy", l: "Paşaköy" },
    { v: "pinarli", l: "Pınarlı" },
    { v: "pirhan", l: "Pirhan" },
    { v: "sakarya", l: "Sakarya" },
    { v: "salamis", l: "Salamis" },
    { v: "serdarli", l: "Serdarlı" },
    { v: "sutluce", l: "Sütlüce" },
    { v: "tatlisu", l: "Tatlısu" },
    { v: "tirmen", l: "Tirmen" },
    { v: "turunclu", l: "Turunçlu" },
    { v: "tuzla", l: "Tuzla" },
    { v: "turkmenkoy", l: "Türkmenköy" },
    { v: "ulukisla", l: "Ulukışla" },
    { v: "vadili", l: "Vadili" },
  ],
  iskele: [
    { v: "agillar", l: "Ağıllar" },
    { v: "altinova", l: "Altınova" },
    { v: "ardahan", l: "Ardahan" },
    { v: "avtepe", l: "Avtepe" },
    { v: "aygun", l: "Aygün" },
    { v: "bafra", l: "Bafra" },
    { v: "bahceler", l: "Bahçeler" },
    { v: "balalan", l: "Balalan" },
    { v: "bogaz", l: "Boğaz" },
    { v: "bogazici", l: "Boğaziçi" },
    { v: "bogaztepe-monarga", l: "Boğaztepe - Monarga" },
    { v: "boltasli", l: "Boltaşlı" },
    { v: "buyukkonuk", l: "Büyükkonuk" },
    { v: "cayirova", l: "Çayırova" },
    { v: "derince", l: "Derince" },
    { v: "dipkarpaz", l: "Dipkarpaz" },
    { v: "ergazi", l: "Ergazi" },
    { v: "esenkoy", l: "Esenköy" },
    { v: "iskele-merkez", l: "İskele Merkez" },
    { v: "kaleburnu", l: "Kaleburnu" },
    { v: "kalecik", l: "Kalecik" },
    { v: "kantara", l: "Kantara" },
    { v: "kaplica", l: "Kaplıca" },
    { v: "kilitkaya", l: "Kilitkaya" },
    { v: "kumyali", l: "Kumyalı" },
    { v: "kurtulus", l: "Kurtuluş" },
    { v: "kuruova", l: "Kuruova" },
    { v: "kuzucuk", l: "Kuzucuk" },
    { v: "long-beach", l: "Long Beach" },
    { v: "mehmetcik", l: "Mehmetçik" },
    { v: "mersinlik", l: "Mersinlik" },
    { v: "otuken", l: "Ötüken" },
    { v: "pamuklu", l: "Pamuklu" },
    { v: "sazlikoy", l: "Sazlıköy" },
    { v: "sinirustu", l: "Sınırüstü" },
    { v: "sipahi", l: "Sipahi" },
    { v: "taslica", l: "Taşlıca" },
    { v: "topcukoy", l: "Topçuköy" },
    { v: "turnalar", l: "Turnalar" },
    { v: "tuzluca", l: "Tuzluca" },
    { v: "yarkoy", l: "Yarköy" },
    { v: "yedikonuk", l: "Yedikonuk" },
    { v: "yeni-erenkoy", l: "Yeni Erenköy" },
    { v: "yesilkoy", l: "Yeşilköy" },
    { v: "ziyamet", l: "Ziyamet" },
  ],
  lefke: [
    { v: "lefke-merkez", l: "Lefke Merkez" },
    { v: "gemikonagi", l: "Gemikonağı" },
    { v: "yesilyurt", l: "Yeşilyurt" },
    { v: "doganci", l: "Doğancı" },
    { v: "akcay", l: "Akçay" },
    { v: "aydinkoy", l: "Aydınköy" },
    { v: "camlikoy", l: "Çamlıköy" },
    { v: "cengizkoy", l: "Cengizköy" },
    { v: "kozankoy", l: "Kozanköy" },
    { v: "taspinar", l: "Taşpınar" },
    { v: "baglikoy", l: "Bağlıköy" },
    { v: "yedidalga", l: "Yedidalga" },
  ],
  guzelyurt: [
    { v: "guzelyurt-merkez", l: "Güzelyurt Merkez" },
    { v: "gemikonagi", l: "Gemikonağı" },
    { v: "yesilyurt", l: "Yeşilyurt" },
    { v: "doganci", l: "Doğancı" },
    { v: "akcay", l: "Akçay" },
    { v: "aydinkoy", l: "Aydınköy" },
  ],
};
