/** KKTC: ilçe (şehir) → bucak (bölge) → yerleşim (mahalle) — admin seçim listeleri */

export type KktcBucak = { name: string; settlements: string[] };
export type KktcIlce = { name: string; bucaklar: KktcBucak[] };

export const KKTC_ILCELER: KktcIlce[] = [
  {
    name: "Lefkoşa",
    bucaklar: [
      {
        name: "Lefkoşa",
        settlements: [
          "Akıncılar",
          "Alayköy",
          "Dilekkaya",
          "Erdemli",
          "Gaziler",
          "Gönyeli",
          "Gürpınar",
          "Hamitköy",
          "Haspolat",
          "İkidere",
          "Kanlıköy",
          "Kırklar",
          "Kırıkkale",
          "Lefkoşa",
          "Türkeli",
          "Yılmazköy",
          "Yiğitler",
        ],
      },
      {
        name: "Değirmenlik",
        settlements: [
          "Beyköy",
          "Balıkesir",
          "Cihangir",
          "Çukurova",
          "Değirmenlik",
          "Demirhan",
          "Düzova",
          "Gaziköy",
          "Gökhan",
          "Kalavaç",
          "Meriç",
          "Minareliköy",
          "Yeniceköy",
        ],
      },
    ],
  },
  {
    name: "Gazimağusa",
    bucaklar: [
      {
        name: "Gazimağusa",
        settlements: [
          "Akova",
          "Alaniçi",
          "Aslanköy",
          "Dörtyol",
          "Gazimağusa",
          "Güvercinlik",
          "Korkuteli",
          "Kurudere",
          "Mormenekşe",
          "Mutluyaka",
          "Pirhan",
          "Şehitler",
          "Yeniboğaziçi",
          "Yıldırım",
        ],
      },
      {
        name: "Geçitkale",
        settlements: [
          "Arıdamı",
          "Çamlıca",
          "Çınarlı",
          "Ergenekon",
          "Geçitkale",
          "Gönendere",
          "Görneç",
          "Mallıdağ",
          "Nergisli",
          "Pınarlı",
          "Serdarlı",
          "Sütlüce",
          "Tirmen",
          "Tatlısu",
          "Ulukışla",
          "Yamaçköy",
        ],
      },
      {
        name: "Akdoğan",
        settlements: [
          "Akdoğan",
          "Beyarmudu",
          "Çayönü",
          "Düzce",
          "İncirli",
          "İnönü",
          "Köprü",
          "Paşaköy",
          "Pile",
          "Turunçlu",
          "Türkmenköy",
          "Vadili",
        ],
      },
    ],
  },
  {
    name: "Girne",
    bucaklar: [
      {
        name: "Girne",
        settlements: [
          "Ağırdağ",
          "Alsancak",
          "Arapköy",
          "Aşağı Dikmen",
          "Aşağı Taşkent",
          "Bahçeli",
          "Beşparmak",
          "Beylerbeyi",
          "Boğazköy",
          "Çatalköy",
          "Dağyolu",
          "Esentepe",
          "Girne",
          "Göçeri",
          "Güngör",
          "Ilgaz",
          "Karaağaç",
          "Karaman",
          "Kömürcü",
          "Karşıyaka",
          "Lapta",
          "Malatya",
          "Ozanköy",
          "Pınarbaşı",
          "Yeşiltepe",
          "Yukarı Dikmen",
          "Yukarı Taşkent",
        ],
      },
      {
        name: "Çamlıbel",
        settlements: [
          "Akçiçek",
          "Akdeniz",
          "Alemdağ",
          "Çamlıbel",
          "Geçitköy",
          "Hisarköy",
          "Karpaşa",
          "Kayalar",
          "Koruçam",
          "Kozanköy",
          "Kılıçarslan",
          "Özhan",
          "Sadrazamköy",
          "Şirinevler",
          "Tepebaşı",
        ],
      },
    ],
  },
  {
    name: "Güzelyurt",
    bucaklar: [
      {
        name: "Güzelyurt",
        settlements: [
          "Akçay",
          "Aydınköy",
          "Gayretköy",
          "Güneşköy",
          "Güzelyurt",
          "Kalkanlı",
          "Mevlevi",
          "Serhatköy",
          "Şahinler",
          "Yayla",
          "Yuvacık",
          "Zümrütköy",
        ],
      },
    ],
  },
  {
    name: "İskele",
    bucaklar: [
      {
        name: "İskele",
        settlements: [
          "Ağıllar",
          "Altınova",
          "Ardahan",
          "Aygün",
          "Boğaziçi",
          "Ergazi",
          "İskele",
          "Kalecik",
          "Kaplıca",
          "Kurtuluş",
          "Kuzucuk",
          "Mersinlik",
          "Ötüken",
          "Sınırüstü",
          "Topcuköy",
          "Turnalar",
          "Yarköy",
        ],
      },
      {
        name: "Mehmetçik",
        settlements: [
          "Bafra",
          "Balalan",
          "Büyükkonuk",
          "Çayırova",
          "Kilitkaya",
          "Kumyalı",
          "Mehmetçik",
          "Pamuklu",
          "Sazlıköy",
          "Tuzluca",
          "Yedikonuk",
          "Zeybekköy",
        ],
      },
      {
        name: "Yeni Erenköy",
        settlements: [
          "Adaçay",
          "Avtepe",
          "Boltaşlı",
          "Derince",
          "Dipkarpaz",
          "Esenköy",
          "Gelincik",
          "Kaleburnu",
          "Kuruova",
          "Sipahi",
          "Taşlıca",
          "Yeni Erenköy",
          "Yeşilköy",
          "Ziyamet",
        ],
      },
    ],
  },
  {
    name: "Lefke",
    bucaklar: [
      {
        name: "Lefke",
        settlements: [
          "Bademköy",
          "Bağlıköy",
          "Cengizköy",
          "Çamlıköy",
          "Doğancı",
          "Erenköy",
          "Gaziveren",
          "Günebakan",
          "Kurutepe",
          "Lefke",
          "Madenliköy",
          "Ömerli",
          "Süleymaniye",
          "Şirinköy",
          "Taşköy",
          "Taşpınar",
          "Yeşilırmak",
          "Yeşilyurt",
        ],
      },
    ],
  },
];

export const KKTC_ILCE_ADLARI = KKTC_ILCELER.map((i) => i.name);

export function kktcBucaklar(ilceAdi: string): KktcBucak[] {
  return KKTC_ILCELER.find((i) => i.name === ilceAdi)?.bucaklar ?? [];
}

export function kktcYerlesimler(ilceAdi: string, bucakAdi: string): string[] {
  const bucak = kktcBucaklar(ilceAdi).find((b) => b.name === bucakAdi);
  return bucak?.settlements ?? [];
}
